# Generated by Django 5.0.6 on 2024-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdb',
            name='country',
            field=models.CharField(default='USA', max_length=120),
        ),
    ]
